In [24]:
import numpy as np

darkfile1 = "/home/sowmya/yolo_computer/darknet/yolov4_tiny/yolov4-tiny_final.weights"  # Pretrained weights file
fp = open(darkfile1, "rb")
ww = np.fromfile(fp,dtype=np.int32)
print(ww[:5])
header=np.fromfile(fp,dtype=np.int32,count=5)
print(header)
w1 = np.fromfile(fp, dtype=np.float32)
fp.close()

[    0     2     5 38400     0]
[]


In [18]:
darkfile2 = "/home/sowmya/yolo_computer/darknet/yolov4_tiny/yolov4-tiny_final2.weights"  # Pretrained weights file
fp = open(darkfile2, "rb")
header=np.fromfile(fp,dtype=np.int32,count=5)
print(header)
w2 = np.fromfile(fp, dtype=np.float32)
fp.close()

[0 0 0 0 0]


In [19]:
np.linalg.norm(w1-w2)

0.0

In [20]:
w2[:4]

array([-0.00705129,  0.01110012, -0.01678175, -0.00561042], dtype=float32)

In [21]:
w1[:4]

array([-0.00705129,  0.01110012, -0.01678175, -0.00561042], dtype=float32)